language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
env:
  global:
  - secure: SmT4+7Xlw65+Gd5fiGK6kfxwc8Xl9AyZizCl7itqbvt/taKdFrdZOeRVhF53dOU/l+YhnQDOP8TgqZQQKK43D3FWuERQf2kQFrBgrxQO3Ao/Mn+GNVDRqNbvmJG1+dMjCJvq6P6SxCHgV2efcSB1gXDIEecbLsd0dwEiikRPJNtHNh3UnM6uAM5ToNnR8/7FwKvSm9kPXrHfQYEsEwnpOj/fb3vJW1KSxW4vqosLullDVOScY1QzrsKT0KDIdkZ7+S8Qy5va8f4EMl9CWuzVGzKXoP5C95vqtclGLtaklcZjKxe5Ir83Tyh6kA5W08M2JFVuHT13mmXXRht3V0tTpbtruNhcFZQlzbsCXa+xpDaD7WXE+C8dc6WnLc+NNOnB8K1dDIk/904j7Q3ERdsl7CufzuCc80yDw2gDKT9RQSQviSlpa4pN4eBtdeMqFFpInjCSPbWoKt7JW42XkrHLAJ0ubGyTGaLjSNTBcdX0eNzvGlOEbKKHl9iIdz7LM4Mj0+UVbSIxHMz0PTA0DWOe0R/h1nJHct9J3dJe2VAaamHbYb4TzdMt6FSh6B25HCU0ynPO+/DrLsmxXksYlNLAkb6R19ox/d9pG0I8vSyABPhVlTgUjItdcuvS8VezyhLIE2MS4s0p8aQetpUwvAzXuAotB76uXekOdhLgh1hMd0k=
  - secure: UcutCU+ukBI4re90zMsWh3eMIzrq370ncVWWlpzXVPE23pEwQSjQagL1BdQBUDEX6PqtR74n+dE2n0Rev8Sk/N+PqILg5J5JBfzB3yMfzPOTHrxQYoV+Xe60Lq+r5n//5zivbY8Ju44tKOnFU2GhNczYJsyqwnq/kjTdtGAVwm4ny0SpAgJRzRKTwV4DEiI7CkotPd1eYdv1P/gUwmiyZY3nQkbrebLCurgPnV33Rl+xGtwt3IRwTEFp3c5Qs7t+jVPBBdrtEqVHKcuLXW3gWfGHvuC0eMeo9yv4SXw+ezCf2pd0HKtZ7IFTouYi9MRxjHCxKNkG+d4rRTeRYHS3lD57fw/jlmkMvhdlXONDdOPQ+3M5P+viadcukhGkU5iHLMM4Uh7OutXO0e1YQit1KH7Pv/tZBcU6wp95YRNoEukd1FL5GDVkrZc//feIXJYXRrRc17Di4FsalkBXN6RpFiync4NEy9bwXxQ46Gx5IriZ5Q2UbGahtN5V2ID/L453m2oMmaecVzsS5sGoUOfcqkW2G4YQURlzFCd7+3KfvoV7uFBou1G14e85laqZmuQFR/5wHIo4bA+6h5pIFiVlnjWnqOPaUOKLIzJcU4IU1rrkfqgs1x/1+KMuu9v/dpzoRzAcRFy69sx+nZLSj3hMfd8Y8QAWSBLIOpTpP16+VDo=
