language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
env:
  global:
  - secure: PJU68WMg4FunQjpcKT8cud4MB3SFDzc4N6tYW8SEZ1t57oU3XjT9OPsjzNWQgkK4+Sd7vQPoL2DijKfJ0aDUCPeSxnK2Cfz+VZgsB5KIFYc7VMiojVad+PzOPaRZn0LojMYBaJsFDoIqjWmvZpWtN6Xwq+KKYghIaj2xFL+bl5iN7X/qe3p7RHASDkw7l+eqsjUD5ebvU9h0P3t8KJWJGBkRUvKieW3d/dndbbOIpSRiV9QafQ9XIUwK/ZedlSD7EQPhk+n2W4SpRZe4IBl5M6A/ncMbeWue58+jtlAYRznj/N8hs06166vGtezGgZzU0WdYZ3xn3ettDBnfa6ZqvtDIdFCDJyFQT1TpqYZNAbDydTSEgp4ZJL6OIDwjzt1Eg9xERt9Za938grzGlLdBpZzWBY1W5J03+j/IvgsXr78/0QP8V2wFMl6sps3AsIvsRKeCzQKj0I5Mby47piyMMFfHrwxptXhV/dYRr4XmoQEN9+ayUqemzvSNx1ug6kUmwOf2o1LaWL3XFk9fExVBcx6obFtyHkfOX18iDPIipfq4ZJ+qE4OJG1YNB1an7ovjotVOgojkPJscT4Mnq3MqLulcaS0IgiVbYDPM5Yws9E+AFWs+6gVPmohd65nchMHJn41rgG7hlAVB2wxAKvPN0yIgD/jZsWZ9QP3406qpRNg=
  - secure: JslL3CHb4XfYb8U887YnSBxD8B+V58WLId1wq1eA0x8XjjvobI1Sb6aS85Th5GSe7k/Ufd8TberKXPaE60DQnZv/cDjgt09R0GuzHZS3EUjvB11zch0ZQ8hUC1rtLKItY+7faQ0zGh2emEXM5dCiCvVaCZIhQND41w2V+sckRgwU74CeT3prBV+0Ymt3KtF1hkVsJd6NQGIjTWvyjhU+ys72f1e0LN4cmfMgbLoicFOMJvOOPTBTl8TQDJIyuG272oFiOUS5N7XQUFiBWpzTpPzil9sKrvj+b/9vXPBTyMk4sV92CK2lCU1m7UZbmmCrBv17mrMfHVi8rVmBoF7SgCtbB0za5YTL6UZErViNWqKJ7cfqWY5CPKB+MdkJZE2FMuQlxITPAIt/ym2HD/UGjyqrAV/6mQqSMKT3vUuViCqab5uwpdB0qwiUsnt8HIHu5IG5fc0zMBH5lESltb9p9/A0oPe0cmacTk6E6VyFg6Cj5WdZTe/O5xzB4VjrzY7bdQO9EOFigxqNo+38O7h2pvA0lBQhpyJc4YS0BKDTsbpeDL5qAQn2eS/BZZnyzNaEqDxLXCBL0E9eGPkL/PWMt6ZCXhJ1iRzNbvzjegWKaQ/JIrnNFjOeoT2nrvx81DU9xhonWEp/+aedfsYGxGpM1AI9jFvxmKY7ley8HEzuv2I=
